// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"golang-example/dao/model"
)

func newUserSpeak(db *gorm.DB, opts ...gen.DOOption) userSpeak {
	_userSpeak := userSpeak{}

	_userSpeak.userSpeakDo.UseDB(db, opts...)
	_userSpeak.userSpeakDo.UseModel(&model.UserSpeak{})

	tableName := _userSpeak.userSpeakDo.TableName()
	_userSpeak.ALL = field.NewAsterisk(tableName)
	_userSpeak.UserID = field.NewInt(tableName, "user_id")
	_userSpeak.LanguageCode = field.NewString(tableName, "language_code")

	_userSpeak.fillFieldMap()

	return _userSpeak
}

type userSpeak struct {
	userSpeakDo

	ALL          field.Asterisk
	UserID       field.Int
	LanguageCode field.String

	fieldMap map[string]field.Expr
}

func (u userSpeak) Table(newTableName string) *userSpeak {
	u.userSpeakDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userSpeak) As(alias string) *userSpeak {
	u.userSpeakDo.DO = *(u.userSpeakDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userSpeak) updateTableName(table string) *userSpeak {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewInt(table, "user_id")
	u.LanguageCode = field.NewString(table, "language_code")

	u.fillFieldMap()

	return u
}

func (u *userSpeak) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userSpeak) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 2)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["language_code"] = u.LanguageCode
}

func (u userSpeak) clone(db *gorm.DB) userSpeak {
	u.userSpeakDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userSpeak) replaceDB(db *gorm.DB) userSpeak {
	u.userSpeakDo.ReplaceDB(db)
	return u
}

type userSpeakDo struct{ gen.DO }

type IUserSpeakDo interface {
	gen.SubQuery
	Debug() IUserSpeakDo
	WithContext(ctx context.Context) IUserSpeakDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserSpeakDo
	WriteDB() IUserSpeakDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserSpeakDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserSpeakDo
	Not(conds ...gen.Condition) IUserSpeakDo
	Or(conds ...gen.Condition) IUserSpeakDo
	Select(conds ...field.Expr) IUserSpeakDo
	Where(conds ...gen.Condition) IUserSpeakDo
	Order(conds ...field.Expr) IUserSpeakDo
	Distinct(cols ...field.Expr) IUserSpeakDo
	Omit(cols ...field.Expr) IUserSpeakDo
	Join(table schema.Tabler, on ...field.Expr) IUserSpeakDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserSpeakDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserSpeakDo
	Group(cols ...field.Expr) IUserSpeakDo
	Having(conds ...gen.Condition) IUserSpeakDo
	Limit(limit int) IUserSpeakDo
	Offset(offset int) IUserSpeakDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserSpeakDo
	Unscoped() IUserSpeakDo
	Create(values ...*model.UserSpeak) error
	CreateInBatches(values []*model.UserSpeak, batchSize int) error
	Save(values ...*model.UserSpeak) error
	First() (*model.UserSpeak, error)
	Take() (*model.UserSpeak, error)
	Last() (*model.UserSpeak, error)
	Find() ([]*model.UserSpeak, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserSpeak, err error)
	FindInBatches(result *[]*model.UserSpeak, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserSpeak) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserSpeakDo
	Assign(attrs ...field.AssignExpr) IUserSpeakDo
	Joins(fields ...field.RelationField) IUserSpeakDo
	Preload(fields ...field.RelationField) IUserSpeakDo
	FirstOrInit() (*model.UserSpeak, error)
	FirstOrCreate() (*model.UserSpeak, error)
	FindByPage(offset int, limit int) (result []*model.UserSpeak, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserSpeakDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userSpeakDo) Debug() IUserSpeakDo {
	return u.withDO(u.DO.Debug())
}

func (u userSpeakDo) WithContext(ctx context.Context) IUserSpeakDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userSpeakDo) ReadDB() IUserSpeakDo {
	return u.Clauses(dbresolver.Read)
}

func (u userSpeakDo) WriteDB() IUserSpeakDo {
	return u.Clauses(dbresolver.Write)
}

func (u userSpeakDo) Session(config *gorm.Session) IUserSpeakDo {
	return u.withDO(u.DO.Session(config))
}

func (u userSpeakDo) Clauses(conds ...clause.Expression) IUserSpeakDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userSpeakDo) Returning(value interface{}, columns ...string) IUserSpeakDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userSpeakDo) Not(conds ...gen.Condition) IUserSpeakDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userSpeakDo) Or(conds ...gen.Condition) IUserSpeakDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userSpeakDo) Select(conds ...field.Expr) IUserSpeakDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userSpeakDo) Where(conds ...gen.Condition) IUserSpeakDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userSpeakDo) Order(conds ...field.Expr) IUserSpeakDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userSpeakDo) Distinct(cols ...field.Expr) IUserSpeakDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userSpeakDo) Omit(cols ...field.Expr) IUserSpeakDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userSpeakDo) Join(table schema.Tabler, on ...field.Expr) IUserSpeakDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userSpeakDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserSpeakDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userSpeakDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserSpeakDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userSpeakDo) Group(cols ...field.Expr) IUserSpeakDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userSpeakDo) Having(conds ...gen.Condition) IUserSpeakDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userSpeakDo) Limit(limit int) IUserSpeakDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userSpeakDo) Offset(offset int) IUserSpeakDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userSpeakDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserSpeakDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userSpeakDo) Unscoped() IUserSpeakDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userSpeakDo) Create(values ...*model.UserSpeak) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userSpeakDo) CreateInBatches(values []*model.UserSpeak, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userSpeakDo) Save(values ...*model.UserSpeak) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userSpeakDo) First() (*model.UserSpeak, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSpeak), nil
	}
}

func (u userSpeakDo) Take() (*model.UserSpeak, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSpeak), nil
	}
}

func (u userSpeakDo) Last() (*model.UserSpeak, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSpeak), nil
	}
}

func (u userSpeakDo) Find() ([]*model.UserSpeak, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserSpeak), err
}

func (u userSpeakDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserSpeak, err error) {
	buf := make([]*model.UserSpeak, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userSpeakDo) FindInBatches(result *[]*model.UserSpeak, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userSpeakDo) Attrs(attrs ...field.AssignExpr) IUserSpeakDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userSpeakDo) Assign(attrs ...field.AssignExpr) IUserSpeakDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userSpeakDo) Joins(fields ...field.RelationField) IUserSpeakDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userSpeakDo) Preload(fields ...field.RelationField) IUserSpeakDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userSpeakDo) FirstOrInit() (*model.UserSpeak, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSpeak), nil
	}
}

func (u userSpeakDo) FirstOrCreate() (*model.UserSpeak, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserSpeak), nil
	}
}

func (u userSpeakDo) FindByPage(offset int, limit int) (result []*model.UserSpeak, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userSpeakDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userSpeakDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userSpeakDo) Delete(models ...*model.UserSpeak) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userSpeakDo) withDO(do gen.Dao) *userSpeakDo {
	u.DO = *do.(*gen.DO)
	return u
}
