Mysql:
  SlowThreshold: 5
  ConnMaxLifetime: 1
  MaxIdleConn: 2
  MaxOpenConn: 2
  ConnMaxIdleTime: 12
  Reade:
    - "root:zhituyunchuang@tcp(127.0.0.1:3316)/gp2?charset=utf8mb4&loc=Local&parseTime=True"
  Write: "root:zhituyunchuang@tcp(127.0.0.1:3316)/gp2?charset=utf8mb4&loc=Local&parseTime=True"