// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	ID        int            `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_accounts_deleted_at,priority:1" json:"deleted_at"`
	UserID    *int           `gorm:"column:user_id;type:bigint unsigned;index:fk_users_account,priority:1" json:"user_id"`
	Number    *string        `gorm:"column:number;type:longtext" json:"number"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
