// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArea = "area"

// Area mapped from table <area>
type Area struct {
	ID          int    `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	AreaInt     string `gorm:"column:area_int;type:json;not null;comment:数组json" json:"area_int"` // 数组json
	AreaString  string `gorm:"column:area_string;type:json;not null" json:"area_string"`
	AreaInt2    string `gorm:"column:area_int_2;type:json;not null;comment:二维数组" json:"area_int_2"`       // 二维数组
	AreaString2 string `gorm:"column:area_string_2;type:json;not null;comment:二维数组" json:"area_string_2"` // 二维数组
	Area        string `gorm:"column:area;type:varchar(255);not null;comment:字符串" json:"area"`            // 字符串
}

// TableName Area's table name
func (*Area) TableName() string {
	return TableNameArea
}
