// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCompany = "companies"

// Company mapped from table <companies>
type Company struct {
	ID   int     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name *string `gorm:"column:name;type:longtext" json:"name"`
}

// TableName Company's table name
func (*Company) TableName() string {
	return TableNameCompany
}
