// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameKec = "kec"

// Kec mapped from table <kec>
type Kec struct {
	ID              int                   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	KecID           string                `gorm:"column:kec_id;type:varchar(50);not null;index:kec_id,priority:1" json:"kec_id"`
	Name            string                `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Cover           string                `gorm:"column:cover;type:varchar(255);not null" json:"cover"`
	CateIds         string                `gorm:"column:cate_ids;type:varchar(255);not null" json:"cate_ids"`
	CateShow        int8                  `gorm:"column:cate_show;type:tinyint;not null;comment:是否显示" json:"cate_show"`           // 是否显示
	Area            string                `gorm:"column:area;type:json;not null;comment:数据地址" json:"area"`                        // 数据地址
	SellerID        int                   `gorm:"column:seller_id;type:int unsigned;not null;comment:课程归属商家的ID" json:"seller_id"` // 课程归属商家的ID
	Desc            string                `gorm:"column:desc;type:text;not null" json:"desc"`
	Lecturer        string                `gorm:"column:lecturer;type:varchar(255);not null" json:"lecturer"`
	LecturerDesc    string                `gorm:"column:lecturer_desc;type:text;not null" json:"lecturer_desc"`
	Num             int                   `gorm:"column:num;type:int unsigned;not null;comment:课程数量" json:"num"`                                         // 课程数量
	RequireNum      int                   `gorm:"column:require_num;type:int unsigned;not null;comment:必修课程数量" json:"require_num"`                       // 必修课程数量
	NotRequireNum   int                   `gorm:"column:not_require_num;type:int unsigned;not null;comment:选修课程数量" json:"not_require_num"`               // 选修课程数量
	RecNum          float64               `gorm:"column:rec_num;type:decimal(10,2) unsigned;not null;comment:推荐学时数量 在课程包的时候等于后者之和" json:"rec_num"`       // 推荐学时数量 在课程包的时候等于后者之和
	RequiredXNum    float64               `gorm:"column:required_x_num;type:decimal(11,2) unsigned;not null;comment:必修学时" json:"required_x_num"`         // 必修学时
	NotRequiredXNum float64               `gorm:"column:not_required_x_num;type:decimal(11,2) unsigned;not null;comment:选修学时" json:"not_required_x_num"` // 选修学时
	PubTime         int                   `gorm:"column:pub_time;type:int unsigned;not null" json:"pub_time"`
	MinPrice        float64               `gorm:"column:min_price;type:decimal(10,2) unsigned;not null" json:"min_price"`
	MaxPrice        float64               `gorm:"column:max_price;type:decimal(10,2) unsigned;not null" json:"max_price"`
	RecPrice        float64               `gorm:"column:rec_price;type:decimal(10,2) unsigned;not null;comment:推荐价格" json:"rec_price"` // 推荐价格
	Level           int                   `gorm:"column:level;type:int unsigned;not null" json:"level"`
	Comment         int8                  `gorm:"column:comment;type:tinyint unsigned;not null" json:"comment"`
	Status          int8                  `gorm:"column:status;type:tinyint unsigned;not null;comment:0未发布1已发布" json:"status"`        // 0未发布1已发布
	IsPackage       int8                  `gorm:"column:is_package;type:tinyint unsigned;not null;comment:0课程1课程包" json:"is_package"` // 0课程1课程包
	CoverFrom       int8                  `gorm:"column:cover_from;type:tinyint;not null;comment:封面来自哪里0自定义1系统" json:"cover_from"`    // 封面来自哪里0自定义1系统
	Duration        int                   `gorm:"column:duration;type:bigint;not null;comment:课程时长" json:"duration"`                  // 课程时长
	CreatedAt       time.Time             `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time             `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint;not null;uniqueIndex:kec_code,priority:2;comment:默认未删除" json:"deleted_at"`      // 默认未删除
	KecCode         string                `gorm:"column:kec_code;type:varchar(255);not null;uniqueIndex:kec_code,priority:1;comment:课程编号--唯一" json:"kec_code"` // 课程编号--唯一
}

// TableName Kec's table name
func (*Kec) TableName() string {
	return TableNameKec
}
