// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLanguage = "languages"

// Language mapped from table <languages>
type Language struct {
	Code string  `gorm:"column:code;type:varchar(191);primaryKey" json:"code"`
	Name *string `gorm:"column:name;type:longtext" json:"name"`
}

// TableName Language's table name
func (*Language) TableName() string {
	return TableNameLanguage
}
