// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameToy = "toys"

// Toy mapped from table <toys>
type Toy struct {
	ID        int            `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_toys_deleted_at,priority:1" json:"deleted_at"`
	Name      *string        `gorm:"column:name;type:longtext" json:"name"`
	OwnerID   *int           `gorm:"column:owner_id;type:bigint unsigned" json:"owner_id"`
	OwnerType *string        `gorm:"column:owner_type;type:longtext" json:"owner_type"`
}

// TableName Toy's table name
func (*Toy) TableName() string {
	return TableNameToy
}
