// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int            `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_users_deleted_at,priority:1" json:"deleted_at"`
	Name      *string        `gorm:"column:name;type:longtext" json:"name"`
	Age       *int           `gorm:"column:age;type:bigint unsigned" json:"age"`
	Birthday  *time.Time     `gorm:"column:birthday;type:datetime(3)" json:"birthday"`
	Area      string         `gorm:"column:area;type:json;not null;comment:数据地址" json:"area"` // 数据地址
	CompanyID *int           `gorm:"column:company_id;type:bigint;index:fk_users_company,priority:1" json:"company_id"`
	ManagerID *int           `gorm:"column:manager_id;type:bigint unsigned;index:fk_users_team,priority:1" json:"manager_id"`
	Active    *int8          `gorm:"column:active;type:tinyint(1)" json:"active"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
