// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserFriend = "user_friends"

// UserFriend mapped from table <user_friends>
type UserFriend struct {
	UserID   int `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`
	FriendID int `gorm:"column:friend_id;type:bigint unsigned;primaryKey;index:fk_user_friends_friends,priority:1" json:"friend_id"`
}

// TableName UserFriend's table name
func (*UserFriend) TableName() string {
	return TableNameUserFriend
}
