// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserSpeak = "user_speaks"

// UserSpeak mapped from table <user_speaks>
type UserSpeak struct {
	UserID       int    `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`
	LanguageCode string `gorm:"column:language_code;type:varchar(191);primaryKey;index:fk_user_speaks_language,priority:1" json:"language_code"`
}

// TableName UserSpeak's table name
func (*UserSpeak) TableName() string {
	return TableNameUserSpeak
}
